import fs from 'node:fs';
const source = JSON.parse(fs.readFileSync(new URL('../src/tokens.json', import.meta.url)));
const out = new URL('../dist/', import.meta.url);
fs.mkdirSync(out, {recursive:true});
const themes = Object.fromEntries(Object.entries(source.themes).map(([mode, values]) => [mode, Object.fromEntries(Object.entries(values).map(([key, ref]) => {
 if (!source.palette[ref]) throw new Error(`Unknown palette reference: ${ref}`);
 return [key,source.palette[ref]];
}))]));
const cssBlock = (selector, values) => `${selector} {\n${Object.entries(values).map(([k,v])=>`  --vs-${k}: ${v};`).join('\n')}\n}\n`;
let css = '/* Generated by scripts/build.mjs. Edit src/tokens.json. */\n';
css += cssBlock(':root', {...source.base,...source.modes.editorial});
for (const [theme,values] of Object.entries(themes)) {
 css += cssBlock(theme === 'paper' ? ':root, [data-vs-theme="paper"]' : `[data-vs-theme="${theme}"]`,values);
 css += `[data-vs-theme="${theme}"] { color-scheme: ${theme === 'dark' ? 'dark':'light'}; }\n`;
}
for (const [mode,values] of Object.entries(source.modes)) css += cssBlock(`[data-vs-mode="${mode}"]`, values);
fs.writeFileSync(new URL('tokens.css',out),css);
const runtime={version:source.version,base:source.base,themes,modes:source.modes,breakpoints:source.breakpoints};
fs.writeFileSync(new URL('tokens.js',out),`// Generated.\nexport const tokens = ${JSON.stringify(runtime,null,2)};\n`);
fs.writeFileSync(new URL('tokens.d.ts',out),`// Generated.\nexport declare const tokens: ${JSON.stringify(runtime,null,2)};\nexport type VesperTheme = keyof typeof tokens.themes;\n`);
const rgb = hex => hex.slice(1).match(/../g).map(v=>parseInt(v,16));
const mix = (hex,target,t) => '#'+rgb(hex).map(v=>Math.round(v*(1-t)+target*t).toString(16).padStart(2,'0')).join('');
let ionic='/* Generated. Import after Ionic core CSS. */\n';
for (const [name,t] of Object.entries(themes)) {
 const vars={'background-color':t.bg,'text-color':t.text,'font-family':'var(--vs-font-ui)','item-background':t.surface,'toolbar-background':t.surface,'toolbar-color':t.text,'border-color':t.border};
 for(const [ionicName,role] of Object.entries({primary:'action',secondary:'info',success:'success',warning:'warning',danger:'danger',medium:'text-muted'})){
  const hex=t[role]; vars[`color-${ionicName}`]=hex; vars[`color-${ionicName}-rgb`]=rgb(hex).join(', ');
  vars[`color-${ionicName}-contrast`]=name==='dark'?themes.dark['on-action']:themes.paper['on-action'];
  vars[`color-${ionicName}-contrast-rgb`]=rgb(vars[`color-${ionicName}-contrast`]).join(', ');
  vars[`color-${ionicName}-shade`]=mix(hex,0,.12); vars[`color-${ionicName}-tint`]=mix(hex,255,.1);
 }
 ionic+=`[data-vs-theme="${name}"] {\n${Object.entries(vars).map(([k,v])=>`  --ion-${k}: ${v};`).join('\n')}\n}\n`;
}
fs.writeFileSync(new URL('ionic.css',out),ionic);
console.log('Generated CSS, typed JavaScript tokens and Ionic themes.');
